
package main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fr4nk
 */
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import sqlite.Sqlite;

public class Icrear extends javax.swing.JInternalFrame {

    /**
     * Creates new form Icrear
     */
    private Sqlite db;
    private principal fmain;
    private String idClase;
    private String idTema;
    
    public Icrear(Sqlite db, principal fmain) {
        this.db = db;
        this.fmain = fmain;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngRespuesta = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtfNombreClase = new javax.swing.JTextField();
        addClase = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tbpanSubtema = new javax.swing.JTabbedPane();
        panSubtema = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfConcepto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAddImgConcepto = new javax.swing.JButton();
        txtfPathImgConcepto = new javax.swing.JTextField();
        lblImgPreview = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfSubtema = new javax.swing.JTextField();
        panEvaluacion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtfPregunta = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAddImgPregunta = new javax.swing.JButton();
        txtfPathImgPregunta = new javax.swing.JTextField();
        lblImgPreviewP = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rbtnOpt1 = new javax.swing.JRadioButton();
        txtfOpt1 = new javax.swing.JTextField();
        txtfOpt2 = new javax.swing.JTextField();
        rbtnOpt2 = new javax.swing.JRadioButton();
        txtfOpt3 = new javax.swing.JTextField();
        rbtnOpt3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAñadirTema = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnAddTema = new javax.swing.JButton();
        txtfTema = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Nombre de la Clase");

        addClase.setText("+");
        addClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClaseActionPerformed(evt);
            }
        });

        txtfConcepto.setColumns(20);
        txtfConcepto.setRows(5);
        jScrollPane1.setViewportView(txtfConcepto);

        jLabel2.setText("Concepto");

        btnAddImgConcepto.setText("Añadir Imagen");
        btnAddImgConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImgConceptoActionPerformed(evt);
            }
        });

        txtfPathImgConcepto.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAddImgConcepto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfPathImgConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(lblImgPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImgPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfPathImgConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddImgConcepto))
                .addContainerGap())
        );

        jLabel5.setText("Titulo");

        javax.swing.GroupLayout panSubtemaLayout = new javax.swing.GroupLayout(panSubtema);
        panSubtema.setLayout(panSubtemaLayout);
        panSubtemaLayout.setHorizontalGroup(
            panSubtemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSubtemaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panSubtemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panSubtemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panSubtemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                        .addComponent(txtfSubtema)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panSubtemaLayout.setVerticalGroup(
            panSubtemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSubtemaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panSubtemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtfSubtema, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panSubtemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSubtemaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2))
                    .addGroup(panSubtemaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbpanSubtema.addTab("Subtema", panSubtema);

        txtfPregunta.setColumns(20);
        txtfPregunta.setRows(5);
        jScrollPane2.setViewportView(txtfPregunta);

        jLabel3.setText("Pregunta");

        btnAddImgPregunta.setText("Añadir Imagen");
        btnAddImgPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImgPreguntaActionPerformed(evt);
            }
        });

        txtfPathImgPregunta.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnAddImgPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfPathImgPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImgPreviewP, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(lblImgPreviewP, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddImgPregunta)
                    .addComponent(txtfPathImgPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btngRespuesta.add(rbtnOpt1);
        rbtnOpt1.setText("Opcion1");

        btngRespuesta.add(rbtnOpt2);
        rbtnOpt2.setText("Opcion2");

        btngRespuesta.add(rbtnOpt3);
        rbtnOpt3.setText("Opcion3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rbtnOpt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfOpt1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rbtnOpt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfOpt2, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rbtnOpt3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfOpt3, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnOpt1)
                    .addComponent(txtfOpt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnOpt2)
                    .addComponent(txtfOpt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnOpt3)
                    .addComponent(txtfOpt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Imagen");

        jLabel6.setText("Respuesta");

        btnAñadirTema.setText("Añadir SubTema");
        btnAñadirTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirTemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEvaluacionLayout = new javax.swing.GroupLayout(panEvaluacion);
        panEvaluacion.setLayout(panEvaluacionLayout);
        panEvaluacionLayout.setHorizontalGroup(
            panEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEvaluacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEvaluacionLayout.createSequentialGroup()
                        .addGroup(panEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panEvaluacionLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEvaluacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAñadirTema)
                .addContainerGap())
        );
        panEvaluacionLayout.setVerticalGroup(
            panEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEvaluacionLayout.createSequentialGroup()
                .addGroup(panEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEvaluacionLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panEvaluacionLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3)))
                .addGroup(panEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEvaluacionLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel4))
                    .addGroup(panEvaluacionLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panEvaluacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEvaluacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAñadirTema)
                .addContainerGap())
        );

        tbpanSubtema.addTab("Evaluación", panEvaluacion);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1147, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        tbpanSubtema.addTab("+", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpanSubtema)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpanSubtema, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnAddTema.setText("+");
        btnAddTema.setEnabled(false);
        btnAddTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTemaActionPerformed(evt);
            }
        });

        txtfTema.setEnabled(false);

        jLabel7.setText("Tema");

        jMenu1.setText("Crear");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfNombreClase)
                .addGap(18, 18, 18)
                .addComponent(addClase)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfTema, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddTema)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addClase))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnAddTema))
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiartext(){
        this.txtfConcepto.setText("");
        this.txtfOpt1.setText("");
        this.txtfOpt2.setText("");
        this.txtfOpt3.setText("");
        this.txtfPathImgConcepto.setText("");
        this.txtfSubtema.setText("");
        this.txtfPregunta.setText("");
        this.txtfPathImgPregunta.setText("");
        this.btngRespuesta.clearSelection();
    }
    
    void setPanelEnabled(JPanel panel, Boolean isEnabled) {
        panel.setEnabled(isEnabled);

        Component[] components = panel.getComponents();

        for (Component component : components) {
            if (component instanceof JPanel) {
                setPanelEnabled((JPanel) component, isEnabled);
            }
            component.setEnabled(isEnabled);
        }
    }
    private void btnAñadirTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTemaActionPerformed
//Path carpeta de las imagenes de las clases
        File pathImg = new File("src/main/images/");
        String path = pathImg.getAbsolutePath();
        
        //Extracción de los atributos
        String respuesta="";
        String PREGUNTA;
        String subtema= this.txtfSubtema.getText();
        String concepto= this.txtfConcepto.getText();
        String pregunta= this.txtfPregunta.getText();
        String imgConcepto= this.txtfPathImgConcepto.getText();
        String imgPregunta= this.txtfPathImgPregunta.getText();
        Integer idSubtema= Integer.valueOf(fmain.extractColumn("subtemas","id_tema","WHERE id_subtema= (SELECT max(id_subtema) FROM subtemas)"));
        String opt1= this.txtfOpt1.getText();
        String opt2= this.txtfOpt2.getText();
        String opt3= this.txtfOpt3.getText();
        //Extracción de la respuesta de selección multiple
        if(this.rbtnOpt1.isSelected()){
            respuesta="Opt1";
        }else if(this.rbtnOpt2.isSelected()){
                respuesta="Opt2";
        }else if (this.rbtnOpt3.isSelected()){
            respuesta="Opt3";
        }
        
        //Formateo de la pregunta
        PREGUNTA= pregunta+"\n"+ opt1+"\n"+ opt2+"\n"+opt3;
        
        String cImgExt= null;
        String pImgExt= null;
        
        if(!imgConcepto.equals("")){
            File origenC= new File(imgConcepto);
            //Formatear cadena para extraer la extension de imgConcepto e imgPregunta
            cImgExt= imgConcepto.substring(imgConcepto.lastIndexOf("."));
            //Importar imagenes
            File destinoC= new File(path+"/c"+String.valueOf(idSubtema+1)+cImgExt);
            fmain.copy(origenC,destinoC);
        }
        if(!imgPregunta.equals("")){
            pImgExt=imgPregunta.substring(imgPregunta.lastIndexOf("."));       
            File destinoP= new File(path+"/p"+String.valueOf(idSubtema+1)+pImgExt);
            File origenP= new File(imgPregunta);

            fmain.copy(origenP, destinoP);
        }
       
        
        //Path de la imagen accesible desde recursos
        imgConcepto="images/c"+String.valueOf(idSubtema+1)+cImgExt;
        imgPregunta="images/p"+String.valueOf(idSubtema+1)+pImgExt;
        
        if(subtema.equals("") || concepto.equals("") || pregunta.equals("")|| respuesta.equals("")){
            JOptionPane.showMessageDialog(null, "Campos Obligatorios Incompletos");
        }else{
            String preQuery="insert into subtemas ( id_tema, id_clase, titulo, concepto, pregunta, img_concepto, img_pregunta, respuesta) values (\'%s\',\'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\', \'%s\');";
            String query= String.format(preQuery,idTema, idClase, subtema, concepto, PREGUNTA, imgConcepto, imgPregunta, respuesta);
            db.setQuery(query);
             JOptionPane.showMessageDialog(null, "Subtema Agregado!");
             limpiartext();
        }
      
    }//GEN-LAST:event_btnAñadirTemaActionPerformed

    private void btnAddImgConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImgConceptoActionPerformed
      
        JFileChooser archivo = new JFileChooser();
        int ventana = archivo.showOpenDialog(null);
        if(ventana == JFileChooser.APPROVE_OPTION){
            File imagen = archivo.getSelectedFile();
            this.txtfPathImgConcepto.setText(String.valueOf(imagen));
            Image foto = getToolkit().getImage(txtfPathImgConcepto.getText());
            foto = foto.getScaledInstance(110,110, Image.SCALE_DEFAULT);
            this.lblImgPreview.setIcon(new ImageIcon(foto) );
        }
        
    }//GEN-LAST:event_btnAddImgConceptoActionPerformed

    private void addClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClaseActionPerformed
        String addClase="insert into clases (nombre_clase) values ('"+ txtfNombreClase.getText() +"')";
        db.setQuery(addClase);
        idClase=fmain.extractColumn("clases","id_clase","WHERE id_clase= (SELECT max(id_clase) FROM clases)");
        this.addClase.setEnabled(false);
        this.txtfNombreClase.setEditable(false);
        this.txtfTema.setEnabled(true);
        this.btnAddTema.setEnabled(true);
                
    }//GEN-LAST:event_addClaseActionPerformed

    private void btnAddTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTemaActionPerformed
        String tema= this.txtfTema.getText();
        db.setQuery("insert into temas (nombre_tema, id_clase) values('"+ tema +"', "+ idClase+")");
        idTema=fmain.extractColumn("temas","id_tema","WHERE id_tema= (SELECT max(id_tema) FROM temas)");
        this.btnAddTema.setEnabled(false);
        this.txtfTema.setEditable(false);
        this.setPanelEnabled(this.panSubtema,true);
        this.setPanelEnabled(this.panEvaluacion,true);
    }//GEN-LAST:event_btnAddTemaActionPerformed

    private void btnAddImgPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImgPreguntaActionPerformed
        JFileChooser archivo = new JFileChooser();
        int ventana = archivo.showOpenDialog(null);
        if(ventana == JFileChooser.APPROVE_OPTION){
            File imagen = archivo.getSelectedFile();
            this.txtfPathImgPregunta.setText(String.valueOf(imagen));
            Image foto = getToolkit().getImage(txtfPathImgPregunta.getText());
            foto = foto.getScaledInstance(110,110, Image.SCALE_DEFAULT);
            this.lblImgPreviewP.setIcon(new ImageIcon(foto) );
        }
        
        
    }//GEN-LAST:event_btnAddImgPreguntaActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        this.setPanelEnabled(this.panSubtema,false);
        this.setPanelEnabled(this.panEvaluacion,false);
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClase;
    private javax.swing.JButton btnAddImgConcepto;
    private javax.swing.JButton btnAddImgPregunta;
    private javax.swing.JButton btnAddTema;
    private javax.swing.JButton btnAñadirTema;
    private javax.swing.ButtonGroup btngRespuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImgPreview;
    private javax.swing.JLabel lblImgPreviewP;
    private javax.swing.JPanel panEvaluacion;
    private javax.swing.JPanel panSubtema;
    private javax.swing.JRadioButton rbtnOpt1;
    private javax.swing.JRadioButton rbtnOpt2;
    private javax.swing.JRadioButton rbtnOpt3;
    private javax.swing.JTabbedPane tbpanSubtema;
    private javax.swing.JTextArea txtfConcepto;
    private javax.swing.JTextField txtfNombreClase;
    private javax.swing.JTextField txtfOpt1;
    private javax.swing.JTextField txtfOpt2;
    private javax.swing.JTextField txtfOpt3;
    private javax.swing.JTextField txtfPathImgConcepto;
    private javax.swing.JTextField txtfPathImgPregunta;
    private javax.swing.JTextArea txtfPregunta;
    private javax.swing.JTextField txtfSubtema;
    private javax.swing.JTextField txtfTema;
    // End of variables declaration//GEN-END:variables

    void setMaximun(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
